# Generated by Django 4.2.4 on 2023-08-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_usertokenpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertokenpassword",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
